spring.application.name=app_biblioteca_api

server.port=8081

spring.datasource.url=jdbc:h2:mem:biblioteca
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
# Inicialização do DB ocorre após a config do datasource

spring.sql.init.mode=always
# Execução dos scripts de inicialização sejam executados no mesmo banco
# de dados em memória

sprint.jpa.show.sql=true
# Habilita a exibição de consultas no console