INSERT  INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Java para Web', 'Willian Abolt', FALSE, NULL);
INSERT  INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Ana', 'Araujo', FALSE, NULL);
INSERT  INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Isabela', 'Jacob', FALSE, NULL);
INSERT  INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Diogo', 'Samuel', TRUE, '2026-04-10');
INSERT  INTO LIVROS (TITULO, AUTOR, EMPRESTADO, DATA_EMPRESTIMO) VALUES ('Giulia', 'Rokicki', FALSE, NULL);